apiVersion: v1
kind: Service
metadata:
  name: mydotnetapp
  namespace: namespace-workflow-1697130820079
spec:
  type: LoadBalancer
  selector:
    app: mydotnetapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080